### ISSUE TITLE
Border around tooltip filled with solid color (only on some views)

### ISSUE THREAD

**Issue by gajicm93** [douglasjunior/android-simple-tooltip#15]
Please see the screenshot:

http://i68.tinypic.com/ao7r47.jpg

**Comment by douglasjunior** [comment]
Your link is not working.

You can add a Custom content to the Tooltip, that's not what you looking for?

**Comment by gajicm93** [comment]
No, I want to use normal built in functionality, but there's a bug with it. Try this link: http://tinypic.com/r/ao7r47/9

![ao7r47](https://cloud.githubusercontent.com/assets/1512341/17327123/48dc4636-588c-11e6-9700-452ba79afc97.jpg)

Thanks.

**Comment by douglasjunior** [comment]
I got it, thanks for the suggestion.

I will look at this in the next modifications.

Thank you.

_Feel free to send a pull request, if you want._

**Comment by douglasjunior** [comment]
@gajicm93, could you post the code that you used, and the library version?

**Comment by gajicm93** [comment]
I don't think you understand me. This silver box around the tooltip is showing for unknown reason, and I don't want it to show. It's a bug.

I used just the most ordinary code:

```
new SimpleTooltip.Builder(this)
.anchorView(yourView)
.text("Texto do Tooltip")
.gravity(Gravity.END)
.animated(true)
.transparentOverlay(true)
.build()
.show();
```

**Comment by douglasjunior** [comment]
Have any other thing different in your environment. This background is always transparent. The color is only changed in overlay mode.

Could you provide more details about the version of Android, device model, emulator, library version, etc?

I saw you had a similar problem with another library. This would not be a setting of your theme?

You could create a sample project to simulate?

**Comment by gajicm93** [comment]
Yeah I did have the same problem with another library, and it probably picks something from my theme, but it shouldn't. An interesting thing is that it does that only for some of the views, and it picks the color the view has (in this picture it picked gray color because the button is gray).

But I fixed it in another library by modifying the library source and by setting backgroundResource to 0 or null, for all the views library creates, so the problem might be the same here.

Generally, I think the problem is that Tooltip picks the background color from theme or the view it is showing for, but it shouldn't.. And I fixed it by explicitly always setting the background to null.

**Comment by douglasjunior** [comment]
I think that this problem is related with `alpha (translucent)`. I dont know why, but the problem is lack of transparency. The background color of `PopupWindow` is configured on [this line](https://github.com/douglasjunior/android-simple-tooltip/blob/fa26793a90f15d12cb96cb39d053256bd877c8a8/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/SimpleTooltip.java#L153).

``` java
mPopupWindow.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
```

And the same problem happens in the `Content Layout` background, created on [this line](https://github.com/douglasjunior/android-simple-tooltip/blob/fa26793a90f15d12cb96cb39d053256bd877c8a8/library/src/main/java/io/github/douglasjunior/androidSimpleTooltip/SimpleTooltip.java#L231). But in the `Content Layout`, the color is not configured, because the default is `TRANSPARENT`.

In this image, you can see the PopupWindow background RED, and the ContentLayout background GREEN. Both have the problem.

![tooltip](https://cloud.githubusercontent.com/assets/1512341/17363454/fac78044-5950-11e6-84c4-ed62c43c885c.png)   ![tooltip1](https://cloud.githubusercontent.com/assets/1512341/17363468/08a8ef68-5951-11e6-8772-e23c959f273b.png)

You tried to run the sample app on your device? Or tried to run your application in the emulator? This lack of transparency seems some Android configuration.

**EDIT:**

I found [this question](http://stackoverflow.com/questions/35928247/transparent-dialog-doesnt-work-in-some-devices) with some informations.

**Comment by douglasjunior** [comment]
@gajicm93 Did you get any solution? Any news?

**Comment by douglasjunior** [comment]
I believe that this issue is out of our reach at the moment, if you find something, please let me know.
