### ISSUE TITLE
How to center text horizontally?

### ISSUE THREAD

**Issue by Grch** [douglasjunior/android-simple-tooltip#23]
Hi! I've tried to override a style like:

```
<style name="simpletooltip_default" parent="@android:style/TextAppearance">
        <item name="android:gravity">center_horizontal</item>
        <item name="android:layout_centerHorizontal">true</item>
        <item name="android:layout_centerInParent">true</item>
    </style>
```

but nothing affects. Can you please help?

**Comment by douglasjunior** [comment]
With default `TextView` is not possible, because this is `wrap_content`.

You need to create a custom content `layout` with a `TextView` as your need.

``` java
   SimpleTooltip tooltip = new SimpleTooltip.Builder(this)
         .anchorView(v)
         .text("Your text here")
         .gravity(Gravity.TOP)
         .contentView(R.layout.your_custom_layout, R.id.textview_in_custom_layout)
         .build();
```

Sample here https://github.com/douglasjunior/android-simple-tooltip/blob/master/sample/src/main/java/io/github/douglasjunior/androidSimpleTooltip/sample/MainActivity.java#L161

Let me know if you need more help 😄
