### ISSUE TITLE
token null is not valid

### ISSUE THREAD

**Issue by micabytes** [douglasjunior/android-simple-tooltip#9]
Seeing the following issue:

Fatal Exception: `android.view.WindowManager$BadTokenException
Unable to add window -- token null is not valid; is your activity running?`

With the stack trace:

``` java
android.view.ViewRootImpl.setView (ViewRootImpl.java:576)
android.widget.PopupWindow.showAtLocation (PopupWindow.java:861)
io.github.douglasjunior.androidSimpleTooltip.SimpleTooltip$1.run (SimpleTooltip.java:166)
android.os.Handler.handleCallback (Handler.java:739)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:703)
```

I suspect it may be something hitting when the app is interrupted and/or closed while in the process of spawning the tooltip, but I haven't had time to investigate yet. Thought I'd mention it, though.

This is with the latest version.

**Comment by douglasjunior** [comment]
Yes, some problems are inevitable. See [known](https://github.com/douglasjunior/android-simple-tooltip#known-issues).

This is because the `root view` of `anchor view` is invalid. It may be because you showed the tooltip before the `activity/dialog` is created, or after the `activity/dialog` is closed.

I'm doing some alternatives to avoid this soon, but the ideal is that you make sure that the display order is correct.

You could find what event that triggered this call?

**Comment by douglasjunior** [comment]
Please, try with branch [issue-9](https://github.com/douglasjunior/android-simple-tooltip/tree/issue-9)

or

``` javascript
compile 'com.github.douglasjunior:android-simple-tooltip:issue-9-SNAPSHOT'
```

**Comment by micabytes** [comment]
Sorry for not getting back about this. Totally forgot about it.

I think the proposed fix worked - the problem disappeared after I implemented this fix. I just recently updated the ToolTip code I'm using, though, and the problem has reappeared (forgot to carry forward the fix). I'll reimplement it now, and will try to remember to get back here if it works as I expect.

**Comment by douglasjunior** [comment]
Ok, I'll be waiting, thank you.

**Comment by michaeloa** [comment]
Zero crashes since I reimplemented this fix from more than a thousand sessions. I'd say this works as intended.

**Comment by micabytes** [comment]
Zero crashes since I reimplemented this fix from more than a thousand sessions. I'd say this works as intended.

**Comment by douglasjunior** [comment]
Good news! @micabytes thank you very much!

**Comment by ripern** [comment]
@douglasjunior I'm using https://github.com/ViHtarb/Tooltip and after getting the same error described in this issue I searched for a solution and found this issue (even though different library).

Seeing the fix you did here, https://github.com/douglasjunior/android-simple-tooltip/commit/b8bc55fa6fb8f17355830f3b678a40756be6d767, do you think a similar fix would solve the same problem in https://github.com/ViHtarb/Tooltip/blame/master/library/src/main/java/com/tooltip/Tooltip.java#L211 ?

Since both are using PopupWindow I figured it would be the same error pretty much.

**Comment by douglasjunior** [comment]
Hi @ripern, this problem is related to PopupWindow and any other Dialog derived in Android. I just added an extra check to try to avoid this problems https://github.com/douglasjunior/android-simple-tooltip/commit/f809d7324c8b83225443acba664741d8b5a051f8, but you need to work to prevent this in your own code too. 

Open a Dialog or PopupWindow after the Activity be finished, or finish an Activity while the PopupWindow/Dialog is open, may cause problems.

See the [known issues](https://github.com/douglasjunior/android-simple-tooltip#known-issues).
